spring:
  config:
    activate:
      on-profile: "security"
jwt:
  access-token-private-key: ${JWT_ACCESS_TOKEN_PRIVATE_KEY}
  access-token-public-key: ${JWT_ACCESS_TOKEN_PUBLIC_KEY}
  refresh-token-secret: ${JWT_REFRESH_TOKEN_SECRET}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME:7200}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME:172800}
  issuer: ${JWT_ISSUER:irum}